msg = '[BVT 1.0] Running page table test.'
echo $msg
decho $msg
dumppages

msg = '[BVT 1.1] Running ram disk contents test.'
echo $msg
decho $msg
if (false) {
    disk
}
dumppages

msg = '[BVT 1.2] Running sound driver test.'
echo $msg
decho $msg
play
dumppages

msg = '[BVT 0.8] Running tasklist.'
echo $msg
decho $msg
tasklist
dumppages

msg = '[BVT 1.3] Running warmboot test.'
echo $msg
decho $msg
warmboot
