//////////////////////////////////////////////////////////////////////////////
//
//  inifile.h - Parser/Iterator for ini file generated by DistroBuilder
//
//  Copyright (c) Microsoft Corporation.  All rights reserved.
//
//  Note: The format is assumed to be a bunch of #-prefixed
//  comment lines followed by space delimited lines describing
//  files thus:
//
//   Hash-MD5=XXX Size=XXX Path=XXX/YYY/ZZZ
//

#ifndef __INIFILE_H__
#define __INIFILE_H__

#include "singldr.h"

struct __near IniFile
{
  private:
    LPUINT8 _pBuffer;
    LPUINT8 _pBufferEnd;
    LPUINT8 _pCurrent;

    IniFile();
    IniFile(const IniFile&);

  public:
    IniFile(LPUINT8 pBuffer, UINT32 cbBuffer) __far;

    void   Rewind() __far;
    bool   MoveNext() __far;

    LPUINT8 GetCurrentFileName() __far;
    UINT32  GetCurrentFileSize() __far;

    UINT16 GetFileCount() __far;
    UINT32 GetTotalBytes() __far;
};

#endif // __INIFILE_H__
